FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -U pip && pip install -r requirements.txt
COPY . .
ENV PYTHONPATH=/app
CMD ["sh", "-c", "python scripts/get_data.py && python scripts/preprocess_data.py"]
