FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -U pip && pip install -r requirements.txt
COPY src ./src
COPY models ./models
COPY artifacts ./artifacts
ENV PYTHONPATH=/app/src
EXPOSE 8000
CMD ["uvicorn", "src.service.main:app", "--host", "0.0.0.0", "--port", "8000"]