FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -U pip && pip install -r requirements.txt && pip install jupyter
COPY src ./src
COPY data ./data
ENV PYTHONPATH=/app/src
CMD ["python", "-m", "ipykernel_launcher", "-f", "/dev/null"]